global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth_service:8000']

  - job_name: 'achat_service'
    static_configs:
      - targets: ['achat_service:8000']
