name: CI/CD Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: main_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r auth_service/requirement.txt
        pip install -r vente_service/requirement.txt
        pip install -r achat_service/requirement.txt
        pip install -r stock_service/requirement.txt
        pip install -r facture_service/requirement.txt

    - name: Run Django tests
      run: |
        cd auth_service
        python manage.py test
        cd ../vente_service
        python manage.py test
        cd ../achat_service
        python manage.py test

    - name: Build Docker Images
      run: |
        docker build -t auth_service ./auth_service
        docker build -t vente_service ./vente_service
        docker build -t achat_service ./achat_service
        docker build -t stock_service ./stock_service
        docker build -t facture_service ./facture_service
